config/routes.rb
Rails.application.routes.draw do
  resources :quotes
  resources :articles
  resources :codes
  resources :companies
  devise_for :users
  root "pages#home"
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :notes, as: :noteable
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  def index
    @articles = Article.all
  end

  # GET /articles/1
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article, notice: 'Article was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /articles/1
  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /articles/1
  def destroy
    @article.destroy
    redirect_to articles_url, notice: 'Article was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def article_params
      params.require(:article).permit(:name, :summary, :link)
    end
end

app/views/articles/_form.html.slim
= simple_form_for(@article) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :summary
    = f.input :link

  .form-actions
    = f.button :submit, class: 'btn btn-success'

app/views/articles/edit.html.slim
h1 Editing article

= render "form"

.btn-group
  = link_to "Show", @article, class: "btn btn-default"
  = link_to "Back", articles_path, class: "btn btn-default"

app/views/articles/index.html.slim
h1 
  | Articles
  = link_to "New Article", new_article_path, class: "btn btn-primary"

table.table.table-striped
  thead
    tr
      th Name
      th Summary
      th Link
      th
      th
      
  tbody
    - @articles.each do |article|
      tr
        td= article.name
        td= article.summary
        td= article.link
        td= link_to "Show", article
        td
          = link_to "Edit", edit_article_path(article)
          '
          |/
          '
          = link_to "Destroy", article, method: :delete, data: { confirm: "Are you sure?" }

app/views/articles/new.html.slim
h1 New article

= render "form"

= link_to "Back", articles_path, class: "btn btn-default"

app/views/articles/show.html.slim
table.table.table-striped
  tr
    th Name:
    td= @article.name
  tr
    th Summary:
    td= @article.summary
  tr
    th Link:
    td= @article.link

.btn-group
  = link_to "Edit", edit_article_path(@article), class: "btn btn-default"
  = link_to "Back", articles_path, class: "btn btn-default"