config/routes.rb
Rails.application.routes.draw do
  resources :quotes
  resources :articles
  resources :codes
  resources :companies
  devise_for :users
  root "pages#home"
end

app/models/code.rb
class Code < ActiveRecord::Base
  belongs_to :company
  has_many :notes, as: :noteable
  has_many :quotes, dependent: :destroy

  before_save :format_symbol

  validates :symbol, presence: true, uniqueness: { case_sensitive: false }

  def to_s
    symbol
  end

  def format_symbol
    self.symbol = symbol.upcase
  end
end

app/controllers/codes_controller.rb
class CodesController < ApplicationController
  before_action :set_code, only: [:show, :edit, :update, :destroy]

  def index
    @codes = Code.all
  end

  def show
  end

  def new
    @code = Code.new
  end

  def edit
  end

  def create
    @code = Code.new(code_params)

    if @code.save
      redirect_to @code, notice: 'Code was successfully created.'
    else
      render :new
    end
  end

  def update
    if @code.update(code_params)
      redirect_to @code, notice: 'Code was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @code.destroy
    redirect_to codes_url, notice: 'Code was successfully destroyed.'
  end

  private
    def set_code
      @code = Code.find(params[:id])
    end

    def code_params
      params.require(:code).permit(:company_id, :symbol, :description, :market)
    end
end

app/views/codes/_form.html.slim
= simple_form_for(@code) do |f|
  = f.error_notification

  .form-inputs
    = f.association :company
    = f.input :symbol
    = f.input :description
    = f.input :market

  .form-actions
    = f.button :submit, class: 'btn btn-success'

app/views/codes/edit.html.slim
h1 Editing code

= render "form"

.btn-group
  = link_to "Show", @code, class: "btn btn-default"
  = link_to "Back", codes_path, class: "btn btn-default"

app/views/codes/index.html.slim
h1 
  | Codes
  = link_to "New Code", new_code_path, class: "btn btn-primary"

table.table.table-striped
  thead
    tr
      th Company
      th Symbol
      th Description
      th
      th
      
  tbody
    - @codes.each do |code|
      tr
        td= code.company
        td= code.symbol
        td= code.description
        td= link_to "Show", code
        td
          = link_to "Edit", edit_code_path(code)
          '
          |/
          '
          = link_to "Destroy", code, method: :delete, data: { confirm: "Are you sure?" }

app/views/codes/new.html.slim
h1 New code

= render "form"

= link_to "Back", codes_path, class: "btn btn-default"

app/views/codes/show.html.slim
table.table.table-striped
  tr
    th Company:
    td= @code.company
  tr
    th Symbol:
    td= @code.symbol
  tr
    th Description:
    td= @code.description
  - unless @code.quotes.empty?
    tr
      th Most Recent Quote:
      td
        table.table-bordered
          tbody
            - @code.quotes.last.json.each do |k, v|
              tr
                th = Quote.tradeking_json_map[k]
                td = v

.btn-group
  = link_to "Edit", edit_code_path(@code), class: "btn btn-default"
  = link_to "Back", codes_path, class: "btn btn-default"