config/routes.rb
Rails.application.routes.draw do
  resources :quotes
  resources :articles
  resources :codes
  resources :companies
  devise_for :users
  root "pages#home"
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :codes, dependent: :destroy
  has_many :notes, as: :noteable
  accepts_nested_attributes_for :codes, reject_if: :all_blank, allow_destroy: true

  def to_s
    name
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  def index
    @companies = Company.all
  end

  # GET /companies/1
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  def create
    @company = Company.new(company_params)

    if @company.save
      redirect_to @company, notice: 'Company was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /companies/1
  def update
    if @company.update(company_params)
      redirect_to @company, notice: 'Company was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /companies/1
  def destroy
    @company.destroy
    redirect_to companies_url, notice: 'Company was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def company_params
      params.require(:company).permit(:name, :description, :link, codes_attributes: [:id, :symbol, :description, :market, :_destroy])
    end
end

app/views/companies/_code_fields.html.slim
.nested-fields
  = f.input :symbol
  = f.input :description
  = f.input :market
  = link_to_remove_association "Remove Symbol", f

app/views/companies/_form.html.slim
= simple_form_for(@company) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :description, as: :text
    = f.input :link

    h3 Symbols
    #codes
      = f.simple_fields_for :codes do |code|
        = render "code_fields", f: code
      .links
        = link_to_add_association "Add Symbol", f, :codes

  .form-actions
    = f.button :submit, class: 'btn btn-success'

app/views/companies/edit.html.slim
h1 Editing company

= render "form"

.btn-group
  = link_to "Show", @company, class: "btn btn-default"
  = link_to "Back", companies_path, class: "btn btn-default"

app/views/companies/index.html.slim
h1 
  | Companies
  = link_to "New Company", new_company_path, class: "btn btn-primary"

table.table.table-striped
  thead
    tr
      th Name
      th Description
      th
      th
      
  tbody
    - @companies.each do |company|
      tr
        td= company.name
        td= company.description
        td= link_to "Show", company
        td
          = link_to "Edit", edit_company_path(company)
          '
          |/
          '
          = link_to "Destroy", company, method: :delete, data: { confirm: "Are you sure?" }

app/views/companies/new.html.slim
h1 New company

= render "form"

= link_to "Back", companies_path, class: "btn btn-default"

app/views/companies/show.html.slim
table.table.table-striped
  tr
    th Name:
    td= @company.name
  tr
    th Description:
    td= @company.description

.btn-group
  = link_to "Edit", edit_company_path(@company), class: "btn btn-default"
  = link_to "Back", companies_path, class: "btn btn-default"